apps/bio/urls.py
from django.urls import path
from .views import about

app_name = "bio"

urlpatterns = [
    path("about/", about, name="about")
]

apps/education/urls.py
from django.urls import path
from . import views

app_name = "education"

urlpatterns = [
    path("", views.educationDetails,name="educationDetails")
]

apps/experience/urls.py
from django.urls import path
from .views import experience

app_name = "experience"

urlpatterns = [
    path("",experience,name="experience"),
]

apps/leads/urls.py
from django.urls import path
from .views import contactView

urlpatterns = [
    path("contact/", contactView, name="contact"),
]

apps/projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.projects, name="projects")
]

apps/skills/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "skills"

urlpatterns = [
    path("",views.skills,name="skills"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import homeView

admin.site.site_header = "Portfolio Admin Portal"
admin.site.site_title = "Portfolio Admin Portal"
admin.site.index_title = "Welcome to Portfolio Admin Portal"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",homeView,name="home"),
    path("bio/", include("apps.bio.urls")),
    path("education/", include("apps.education.urls")),
    path("skills/", include("apps.skills.urls")),
    path("experience/", include("apps.experience.urls")),
    path("projects/", include("apps.projects.urls")),
    path("leads/", include("apps.leads.urls")),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/bio/models.py
from django.db import models

# Create your models here.
class Bio(models.Model):
    name = models.CharField(max_length=200)
    role = models.CharField(max_length=255)
    summary = models.TextField()
    focus_areas = models.CharField(max_length=300)

    def save(self, *args, **kwargs):
        if not self.pk and Bio.objects.exists():
            raise ValueError("Only one Bio instance is allowed")
            
        super(Bio, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Bio'
        verbose_name_plural = 'Bio'
    
    

apps/education/models.py
from django.db import models

# Create your models here.
class Education(models.Model):
    degree_title = models.CharField(max_length=255)
    institute_name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = "Degree"
        verbose_name_plural = "Degrees"

    
    

apps/experience/models.py
from django.db import models

# Create your models here.
class Experience(models.Model):
    company_name = models.CharField(max_length=255)
    company_url = models.URLField(null=True, blank=True,default="#")
    position = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField()


    class Meta:
        verbose_name = "Experience"
        verbose_name_plural = "Experiences"

    def __str__(self):
        return self.company_name
    

apps/leads/models.py
from django.db import models

# Create your models here.
class ContactLeads(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contact Lead'
        verbose_name_plural = 'Contact Leads'
    

apps/projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='projects/')
    technologies = models.CharField(max_length=300)
    github_url = models.URLField(blank=True, null=True)
    linkedin_url = models.URLField(blank=True, null=True)
    
    class Meta:
        verbose_name = "Project"
        verbose_name_plural = "Projects"

    def __str__(self):
        return self.name

apps/skills/models.py
from django.db import models

# Create your models here.
class Skills(models.Model):
    CATEGORY_CHOICES = [
        ('Programming Languages', 'Programming Languages'),
        ('Frontend Technologies', 'Frontend Technologies'),
        ('Backend Frameworks', 'Backend Frameworks'),
        ('Databases', 'Databases'),
        ('Data Science Technologies', 'Data Science Technologies'),
        ('Tools & Platforms', 'Tools & Platforms'),
    ]

    LEVEL_CHOICES = [
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Advanced', 'Advanced'),
    ]
    
    skill_name = models.CharField(max_length=300)
    skill_image = models.ImageField(upload_to='skills/', blank=True, null=True)
    skill_category = models.CharField(max_length=300, choices=CATEGORY_CHOICES)
    skill_level = models.CharField(max_length=200, choices=LEVEL_CHOICES)

    def __str__(self):
        return self.skill_name

    class Meta:
        verbose_name = "Skill"
        verbose_name_plural = "Skills"
    

apps/bio/views.py
from django.shortcuts import render
from .models import Bio

# Create your views here.
def about(request):
    bio = Bio.objects.first()
    return render(request, 'bio/about.html', {'bio': bio})

apps/education/views.py
from django.shortcuts import render
from .models import Education


def educationDetails(request):
    education = Education.objects.all().order_by('-start_date')
    return render(request, 'education/education.html', {'education': education})

apps/experience/views.py
from django.shortcuts import render
from .models import Experience

def experience(request):
    experience = Experience.objects.all().order_by('-start_date')
    return render(request, 'experience/experience.html', {'experience': experience})

apps/leads/views.py
from django.shortcuts import render, redirect
from .models import ContactLeads


# Create your views here.
def contactView(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        ContactLeads.objects.create(name=name, email=email, message=message)
        return render(request, "leads/success.html")    
    return render(request, "leads/contact.html")

apps/projects/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def projects(request):
    projects = Project.objects.all()
    return render(request, 'projects/projects.html', {'projects': projects})

apps/skills/views.py
from django.shortcuts import render
from .models import Skills
# Create your views here.

def skills(request):
    skills = Skills.objects.all().order_by('-skill_category')
    categories_skills_cnt = {}
    for skill in skills:
        if skill.skill_category not in categories_skills_cnt:
            categories_skills_cnt[skill.skill_category] = skills.filter(skill_category=skill.skill_category).count()
    return render(request, 'skills/skills.html', {'skills': skills, 'categories_skills_cnt': categories_skills_cnt})

portfolio/views.py
from django.shortcuts import render


# Home View
def homeView(request):
    return render(request, "project/index.html")

apps/bio/templates/bio/about.html
{% extends 'layout.html' %}
{% load static %}

{% comment %} Linking Static Files {% endcomment %}
{% block linking_files %}
    <link rel="stylesheet" href="{% static 'bio/style.css' %}">
{% endblock %}


{% comment %} Header Content on Top {% endcomment %}
{% block header_content %}About{% endblock %}

{% comment %} Main Content {% endcomment %}
{% block main_content %}
    <div class="about-container">
        <div class="about-msg">
            <h2>Biography</h2>
        </div>
        <div class="about-content">
            <div class="name">
                <h3 class="div-content">Name</h3>
                <h3>{{ bio.name }}</h3>
            </div>
            <div class="role">
                <h3 class="div-content">Role</h3>
                <h3>{{ bio.role }}</h3>
            </div>
            <div class="summary">
                <h3 class="div-content">Summary</h3>
                <p>{{ bio.summary }}</p>
            </div>
            <div class="focus-areas">
                <h3 class="div-content">Focus Areas</h3>
                <p>{{ bio.focus_areas }}</p>
            </div>
        </div>
    </div>
{% endblock %}

apps/education/templates/education/education.html
{% extends 'layout.html' %}
{% load static %}

{% comment %} Linking Static Files {% endcomment %}
{% block linking_files %}
    <link rel="stylesheet" href="{% static 'education/style.css' %}">
{% endblock %}


{% comment %} Header Content on Top {% endcomment %}
{% block header_content %}Education{% endblock %}

{% comment %} Main Content {% endcomment %}
{% block main_content %}
    <div class="education-container">
        <div class="education-msg">
            <h2>Education</h2>
        </div>
        <div class="education-content">
            {% for education in education %}
                <div class="education-item">
                    <h3>{{ education.degree_title }}</h3>
                    <div class="education-item-details">
                        <p>{{ education.institute_name }}</p>
                        {% if education.end_date %}
                            <p>{{ education.start_date|date:"Y" }} - {{ education.end_date|date:"Y" }}</p>
                        {% else %}
                            <p>{{ education.start_date|date:"Y" }} - Present</p>
                        {% endif %}
                        <br>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

apps/experience/templates/experience/experience.html
{% extends 'layout.html' %}
{% load static %}

{% comment %} Linking Static Files {% endcomment %}
{% block linking_files %}
    <link rel="stylesheet" href="{% static 'experience/style.css' %}">
{% endblock %}

{% comment %} Header Content on Top {% endcomment %}
{% block header_content %}Experience{% endblock %}

{% comment %} Main Content {% endcomment %}
{% block main_content %}
    <div class="experience-container">
        <div class="experience-msg">
            <h2>Experience</h2>
        </div>
        <div class="experience-content">
            {% for experience in experience %}
                <div class="experience-item">
                    {% if experience.company_url %}
                        <a href="{{ experience.company_url }}" target="_blank">
                            <h3>{{ experience.company_name }}</h3>
                        </a>
                    {% else %}
                        <h3>{{ experience.company_name }}</h3>
                    {% endif %}
                    <div class="experience-item-details">
                        <p>{{ experience.position }}</p>
                        {% if experience.end_date %}
                            <p>{{ experience.start_date|date:"F Y" }} - {{ experience.end_date|date:"F Y" }}</p>
                        {% else %}
                            <p>{{ experience.start_date|date:"F Y" }} - Present</p>
                        {% endif %}
                        <p>{{ experience.description }}</p>
                        <br>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

apps/leads/templates/leads/contact.html
{% extends 'layout.html' %}
{% load static %}

{% comment %} Linking Static Files {% endcomment %}
{% block linking_files %}
    <link rel="stylesheet" href="{% static 'leads/style.css' %}">
{% endblock %}


{% comment %} Header Content on Top {% endcomment %}
{% block header_content %}Contact{% endblock %}


{% comment %} Main Content {% endcomment %}
{% block main_content %}
    <div class="contact-container">
        <div class="contact-msg">
            <h2>Contact</h2>
        </div>
        <div class="contact-content">
            <h4>Let’s build something meaningful together.</h4>
            <div class="contact-form">
                <form action="{% url 'contact' %}" method="POST" autocomplete="off">
                    {% csrf_token %}
                    <div class="name">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name" required>
                    </div>
                    <div class="email">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" required>
                    </div>
                    <div class="message">
                        <label for="message">Message</label>
                        <textarea name="message" id="message" rows="5" style="resize: none;" required></textarea>
                    </div>
                    <button type="submit">Let's Build</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/leads/templates/leads/success.html
{% extends 'layout.html' %}
{% load static %}

{% block header_content %}Contact{% endblock %}

{% block main_content %}
<div class="contact-container" style="text-align: center; padding-top: 50px; border: 2px solid var(--grey-color); border-radius: 10px; padding: 10px; background-color: var(--secondary-color); width: 50%; margin: auto; margin-top: 20px;">
    <h1>Message Sent!</h1>
    <br>
    <p>Thank you for reaching out. I will get back to you shortly.</p>
    <p style="margin-top: 5px;">Redirecting to home page in <span id="countdown" style="color: var(--blue-color); font-weight: bold;">4</span> seconds...</p>
</div>

<script>
    let seconds = 4;
    const countdownElement = document.getElementById('countdown');
    
    const interval = setInterval(() => {
        seconds--;
        countdownElement.textContent = seconds;
        
        if (seconds <= 0) {
            clearInterval(interval);
            window.location.href = "{% url 'home' %}";
        }
    }, 1500);
</script>
{% endblock %}

apps/projects/templates/projects/projects.html
{% extends 'layout.html' %}
{% load static %}

{% comment %} Linking Static Files {% endcomment %}
{% block linking_files %}
    <link rel="stylesheet" href="{% static 'projects/style.css' %}">
{% endblock %}

{% comment %} Header Content on Top {% endcomment %}
{% block header_content %}Projects{% endblock %}

{% comment %} Main Content {% endcomment %}
{% block main_content %}
    <div class="projects-container">
        <div class="projects-msg">
            <h2>Projects</h2>
        </div>
        <div class="projects-content">
            {% for project in projects %}
                <div class="projects-item">
                    <div class="projects-item-details">
                        <h3>{{ project.name }}</h3>
                        <div class="project-item-content">
                            <p>{{ project.description }}</p>
                            <p id="tech">{{ project.technologies }}</p>
                            <div class="project-item-links">
                                <a href="{{ project.github_url }}"><i class="fab fa-github"></i></a>
                                <a href="{{ project.linkedin_url }}"><i class="fab fa-linkedin"></i></a>
                            </div>
                        </div>
                        <br>
                    </div>
                    <div class="projects-item-image">
                        <img src="{{ project.image.url }}" alt="{{ project.name }}">
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

apps/skills/templates/skills/skills.html
{% extends 'layout.html' %}
{% load static %}

{% comment %} Linking Static Files {% endcomment %}
{% block linking_files %}
    <link rel="stylesheet" href="{% static 'skills/style.css' %}">
{% endblock %}


{% comment %} Header Content on Top {% endcomment %}
{% block header_content %}Skills{% endblock %}

{% comment %} Main Content {% endcomment %}
{% block main_content %}
    <div class="skills-container">
        <div class="skills-msg">
            <h2>Skills</h2>
        </div>
        <div class="skills-content">
            <div class="skills-item">
                <table class="skills-table">
                    <tr style="text-align: center;">
                        <th>Skill</th>
                        <th>Level</th>
                        <th>Category</th>
                        {% if user.is_authenticated %}
                        <th>Actions</th>
                        {% endif %}
                    </tr>
                    <tr>
                        {% for skill in skills %}
                        {% if skill.skill_image %}
                        <td><div><img src="{{ skill.skill_image.url }}" alt="-" width="30" height="30"><span>{{ skill.skill_name }}</span></div></td>
                            {% else %}
                                <td><div><span>{{ skill.skill_name }}</span></div></td>
                                {% endif %}
                                {% if skill.skill_level == 'Beginner' %}
                                <td><span id="skill-level-beginner">{{ skill.skill_level }}</span></td>
                            {% elif skill.skill_level == 'Intermediate' %}
                                <td><span id="skill-level-intermediate">{{ skill.skill_level }}</span></td>
                                {% elif skill.skill_level == 'Advanced' %}
                                <td><span id="skill-level-advanced">{{ skill.skill_level }}</span></td>
                            {% endif %}
                            <td>{{ skill.skill_category }}</td>
                            {% if user.is_authenticated %}
                                <td>
                                    <div style=" display: flex; align-items: center; justify-content: center; gap: 10px;">
                                        <a href="#"><i style=" color: rgba(82, 136, 254, 0.8);" class="fa-regular fa-pen-to-square"></i></a>
                                        <a href="#"><i style=" color: rgba(251, 0, 0, 0.8);" class="fa-solid fa-trash"></i></a>
                                    </div>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </table>
                </div>
        </div>
    </div>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" type="image/x-icon" href="{% static 'project/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block linking_files %}{% endblock %}
    <title>Muhammad Abish Baig</title>
</head>
<body>
    <header>
        {% comment %} Header Top Main Content {% endcomment %}
        <div class="main_head">
            <pre id="const_heading1">{% block header_content %}Home Page{% endblock %}</pre>
            <pre id="const_heading2">- Abish's Portfolio</pre>
        </div>

        {% comment %} Nav Bar {% endcomment %}
        <div class="navbar">
            <div class="tab active">
                <a href="{% url 'home' %}"><i class="fa-brands fa-markdown" style="color: #DE8B48;"></i></a>
                <a href="{% url 'home' %}">Readme.md</a>
            </div>
            <div class="tab">
                <a href="{% url 'bio:about' %}"><i class="fa-brands fa-html5" style="color: #ff6666;"></i></a>
                <a href="{% url 'bio:about' %}">About.html</a>
            </div>
            <div class="tab">
                <a href="{% url 'education:educationDetails' %}"><i class="fa-brands fa-css3" style="color: #4d79ff;"></i></a>
                <a href="{% url 'education:educationDetails' %}">Education.css</a>
            </div>
            <div class="tab">
                <a href="{% url 'skills:skills' %}"><i class="fa-brands fa-node-js" style="color:  #29a329;"></i></a>
                <a href="{% url 'skills:skills' %}">Skills.js</a>
            </div>
            <div class="tab">
                <a href="{% url 'experience:experience' %}"><i class="fa-solid fa-c" style="color: #b3e6ff;"></i></a>
                <a href="{% url 'experience:experience' %}">Experience.c</a>
            </div>
            <div class="tab">
                <a href="{% url 'projects:projects' %}"><i class="fa-brands fa-python" style="color: #FFD43B;"></i></a>
                <a href="{% url 'projects:projects' %}">Projects.py</a>
            </div>
            <div class="tab">
                <a href="{% url 'contact' %}"><i class="fa-regular fa-file"></i></a>
                <a href="{% url 'contact' %}">Contact.log</a>
            </div>
        </div>
    </header> 
    
    {% comment %} Side Bar {% endcomment %}
    <aside>
        <div class="top">
            <a href="{% url 'home' %}"><i class="fa-solid fa-folder"></i></a>
            <a href="{% url 'projects:projects' %}"><i class="fa-solid fa-magnifying-glass"></i></a>                
            <a href="https://github.com/abishbaig"><i class="fa-brands fa-git-alt"></i></a>                
        </div>
        <div class="bottom">
            <div class="sidebar_tab">
                <a href="{% url 'bio:about' %}"><i class="fa-solid fa-user"></i></a>
            </div>
            {% if user.is_authenticated %}
                <div class="sidebar_tab">
                    <a href="/admin/"><i class="fa-solid fa-gear"></i></a>
                </div>
            {% endif %}
        </div>
    </aside>

    <main class="scrollbar-element">
        <div class="main_divider"></div>
        <div class="main_div">
            {% block main_content %}
                
            {% endblock %}       
        </div>
    </main>

    <footer>
        <div class="left_footer">
            <div class="left_footer_content">
                <span>Connect With Me:</span>
                <a href="https://github.com/abishbaig"><i class="fa-brands fa-github"></i></a>
                <a href="https://www.linkedin.com/in/abishbaig/"><i class="fa-brands fa-linkedin-in"></i></a>
                <a href="mailto:baig.abish423@gmail.com"><i class="fa-regular fa-envelope"></i></a>
            </div>
        </div>
        <div class="right_footer">
            <div class="right_footer_content">
                {% block footer_lang %}
                    <span>MARKDOWN</span>
                {% endblock %}
                <span>UTF-8</span>
                <a href="{% url 'contact' %}"><i class="fa-solid fa-bell"></i></a>
            </div>
        </div>
    </footer>
    
    <script src="{% static 'app.js' %}"></script>
</body>
</html>

templates/project/index.html
{% extends "layout.html" %}
{% load static %}

{% comment %} Linking Static Files {% endcomment %}
{% block linking_files %}
    <link rel="stylesheet" href="{% static 'project/style.css' %}">
{% endblock %}

{% comment %} Header Content on Top {% endcomment %}
{% block header_content %}Home{% endblock %}

{% comment %} Main Content {% endcomment %}
{% block main_content %}
    <div class="hero-container">
        <div class="left-container">
            <div class="greetings">
                <h4>Hello World, I am</h4>
            </div>

            <!-- TODO: Add Dynamic Data -->
            <div class="main-content">
                <h1>Muhammad Abish Baig</h1>
                <h3><span>Aspiriring</span> Systems Engineer</h3>
            </div>

            <div class="resume">
                <a href="{% static 'project/files/Resume.pdf' %}" download>Resume.pdf</a>
            </div>
        </div>
        <div class="right-container">
            <img src="{% static 'project/images/pic_frame.png' %}" alt="Picture Frame">
        </div>
    </div>
{% endblock main_content %}